modulo6-Semana4/reserva/urls.py
from django.urls import path

from reserva.views import criar_reserva

app_name = 'reserva'

urlpatterns = [
  path("criar/", criar_reserva, name="criar_reserva"),
]

modulo6-Semana4/ultima/urls.py
from django.contrib import admin
from django.urls import path, include

from base.views import inicio, contato

urlpatterns = [
    path("", inicio, name="inicio"),
    path("contato/", contato, name="contato"),
    path("reserva/", include('reserva.urls', namespace='reserva')),
    path("admin/", admin.site.urls),
]

modulo6-Semana4/base/models.py
from django.db import models

class Contato(models.Model):

  PREFERENCIA_EVENTO_CHOICES = (
    ('todos', 'Todos'),
    ('musicais', 'Eventos Musicais'),
    ('esportivos', 'Eventos Esportivos'),
    ('educativos', 'Eventos Educativos'),
  )

  nome = models.CharField(verbose_name= 'Nome', max_length=50)
  email = models.EmailField(verbose_name= 'E-mail',max_length=100)
  preferencia_evento = models.CharField(
    verbose_name='Preferência de Evento', max_length=20, default='todos',
    choices=PREFERENCIA_EVENTO_CHOICES)
  mensagem = models.TextField(verbose_name= 'Mensagem')
  data = models.DateTimeField(verbose_name= 'Data Envio',auto_now_add=True)
  lido = models.BooleanField(verbose_name='Lido', default=False, blank=True)

  def __str__(self):
    return f'{self.nome} [{self.email}]'
  class Meta:
    verbose_name = 'Formulário de Contato'
    verbose_name_plural = 'Formulários de Contatos'
    ordering = ['-data']

modulo6-Semana4/reserva/models.py
from django.db import models

class Reserva(models.Model):
  TAMANHO_OPCOES = (
    (0, 'Pequeno'),
    (1, 'Médio'),
    (2, 'Grande'),
  )
  TURNO_OPCOES = (
    ('manhã', 'Manhã'),
    ('tarde', 'Tarde'),
  )
  nome = models.CharField(verbose_name='Nome', max_length=50)
  email = models.EmailField(verbose_name='E-mail')
  nome_pet = models.CharField(verbose_name='Nome do Pet', max_length=50)
  data = models.DateField(verbose_name='Data', help_text='dd/mm/aaaa')
  turno = models.CharField(verbose_name='Turno', max_length=10, choices=TURNO_OPCOES)
  tamanho = models.IntegerField(verbose_name='Tamanho', choices=TAMANHO_OPCOES)
  observacoes = models.TextField(blank=True)

  def __str__(self):
    return f'{self.nome}: {self.data} - {self.turno}'
  
  class Meta:
    verbose_name = 'Reserva de Banho'
    verbose_name_plural = 'Reservas de Banho'

modulo6-Semana4/base/forms.py
from django import forms
from base.models import Contato

class ContatoForm(forms.ModelForm):
  class Meta:
    model = Contato
    fields = ['nome', 'email', 'preferencia_evento', 'mensagem']

modulo6-Semana4/reserva/forms.py
from datetime import date
from django import forms
from reserva.models import Reserva


class ReservaForm(forms.ModelForm):
    class Meta:
        model = Reserva
        fields = [
            "nome",
            "email",
            "nome_pet",
            "data",
            "turno",
            "tamanho",
            "observacoes",
        ]

    def clean_data(self):
        data = self.cleaned_data.get("data")
        if Reserva.objects.filter(data=data).count() >= 4:
            raise forms.ValidationError("Limite de reservas para este dia atingido.")
        return data

modulo6-Semana4/base/views.py
from django.shortcuts import render
from base.forms import ContatoForm

def inicio(request):
  return render(request, 'inicio.html')

def contato(request):
  sucesso = False
  form = ContatoForm(request.POST or None)
  if form.is_valid():
      sucesso = True
      form.save()
  contexto = {
    'telefone': '(99) 9999-9999',
    'responsavel': 'Zé linguiça',
    'form': form,
    'sucesso': sucesso
  }
  return render(request, 'contato.html', contexto)

modulo6-Semana4/reserva/views.py
from django.shortcuts import render
from reserva.forms import ReservaForm


def criar_reserva(request):
    form = ReservaForm(request.POST or None)
    sucesso = False
    if form.is_valid():
        form.save()
        sucesso = True
    contexto = {
        "form": form,
        "sucesso": sucesso,
    }
    return render(request, "criar_reserva.html", contexto)

modulo6-Semana4/base/templates/contato.html
{% extends "inicio.html" %} {% load bootstrap5 %} {% block principal %}

<h1>Fale Conosco</h1>
<p>
  Envie uma mensagem através do formulário abaixo ou ligue para o telefone {{
  telefone }} falando com a responsável {{ responsavel }}.
</p>
{% if sucesso %}
<p class="alert alert-success">Mensagem enviada com sucesso!</p>
{% else %}
<form action="" method="post" novalidate>
  {% csrf_token %} {% bootstrap_form form %}
  <hr />
  <button type="submit" class="btn btn-primary">Enviar Mensagem</button>
</form>
<br />
<a href="{% url 'inicio' %}">Voltar</a>
{% endif %} {% endblock %}

modulo6-Semana4/base/templates/inicio.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Pet Online - Reserve já!</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />

    <!-- Style -->
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      header {
        display: flex;
        justify-content: space-between;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img {
          font-size: 3.5rem;
        }
      }
    </style>

    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="{% static 'css/starter-template.css' %}" />
  </head>
  <body>
    <div class="col-lg-8 mx-auto p-3 py-md-5">
      <header class="d-flex align-items-center pb-3 mb-5 border-bottom">
        <a
          href="/"
          class="d-flex align-items-center text-dark text-decoration-none"
        >
          <span class="fs-4">Pet online</span>
        </a>
        <br />
        <a href="{% url 'contato' %}">Fale Conosco</a>
      </header>

      <main>
        {% block principal %}
        <h1>Reserve já o banho do seu Pet</h1>
        <br />
        <a href="{% url 'reserva:criar_reserva' %}" class="btn btn-primary"
          >Fazer Reserva</a
        >
        {% endblock %}
      </main>

      <footer class="pt-5 my-5 text-muted border-top">
        Curso Python Ultima School
      </footer>
    </div>

    <script src="{% static 'js/bootstrap.bundle.min.ja' %}"></script>
  </body>
</html>

modulo6-Semana4/reserva/templates/criar_reserva.html
{% extends "inicio.html" %} {% load bootstrap5 %} {% block principal %}
<h1>Faça a sua reserva</h1>
{% if sucesso %}
<p class="alert alert-success">
  Reserva realizada com sucesso, em breve iremos entrar em contato!
</p>
{% else %}
<form action="" method="post">
  {% csrf_token %} {% bootstrap_form form %}
  <hr />
  <button type="submit" class="btn btn-primary">Realizar Reserva</button>
</form>
{% endif %} {% endblock %}